language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
deploy:
  provider: heroku
  run: rake db:migrate
  app: carrentalz
  on:
    repo: tojawawel/Carrental
  api_key:
    secure: d3GZ8mBYxPZcD9FWR2gwE6PggWHUBajr33jzWLN1unP1teelmnTSD4tRO/rd93Z6kHH1Gxw8E48boiefVvzcZSVfcVjZav/Nx8ufsGT88DDIw6b9ZuRQtUrut/B6k+TDQI0V5U+TxtDR2D8cr8h7qQb2pT+uzgCm0y0YIZYm4kh8G5NSx1++OAFMZFAN/UMe88rJe53qwJ3jo8fvTNrCa5Dny5r8RIVVjgMXI1f1naP2/a+wWhO9zjvz4Ppszcmh1TtRYSzONweRNj+bsmbssj7Vyun4Q1OaGsmvjEfgUiLY4BaunsryTETM6iSb5pA8HEz2UCefF/eME4O29xYUmFw5bakKI4Gm5IdbRIabY24Wo3+9jilnpH8Ou3ya1Yx9xQuUQ7UBBI9CkSoxEh6zTX+51BKSl7gqFXFRG2ydzMlc7ceeoTXrzfcww3OkEdB8kz4ty/YLbwUWYmT9W/0HbNZ5PTGs78BzINNXTA+9l2fLjZTdmy6L1fbYgdhZXCYC7WwE1/Rr9RI+fbbZiO01MTq0yGujB9QWsNf0wTN0wxi6soXu6MwVIaLLR5KTFAOtaZETIkTl9cFNNzgfmqtRRLl99oe4m0g9fmfsd3uvvoBGUN56pxHszs+oxEx+RSTOUXdC6AIigeRznxLXnTO1Ib/0bsuf/vb0XCGu0PjqWEo=
env:
  secure: OYiu5Mj4HWuBVAQYH9Jp5gzi7oqP4RyTtqg7SEecVzIj5Kh53IZc6Iw6f4UsEtUfT/me9LM+ZeXtDiJwsWfnUWUTbuBWVyTHHtBysX5VBh7OC3e/btriMFEx7Rzbb6iI5LLgGB9NlR/nPzLeCF5e0XhvMKPJEEvKHfkPpb9EmU8F6jqRedzXu9eZr6yCYllOB6ygNW3XrGbmPeMO0WdcpS+4hnzHHk/v/LDTcLRUyw+MAN39nb61leolhYXyyIMnSVrIWYYmagS4z2STLxUJwHbRjtsiUI5d3WV0C92Oe17w92syA0tNDCUP6887l88BQkyNYtGgYrDrWB3HRtCtDrB790ew5t9T0pZCY43yLBpP/VcaA5r6GDqzmraVJXVW+a0LuSNKXMXLghuM1iYj0jks2iw/BaNhQEpSQAhoEuBOyaKLyLNl7j4w+FFrBlmv2dn0divke/5f9YQS4JU4tqaIFP8RwqfNH7H3Y86xAjqnvkME2uttik5e6djzfg25b0kM/R2xg6hd3g0inayAIAaNT4RptXISuQ7d+cMZo4rT+45gXPVwxGwInJmQPUyFyctyRGxK0pp/2gpaZFbOK9PVzlmDST+iPJ5d0fCuLmb0Rhoh9VpY5gFKBNdhFOwBT3kbWpLtHWEZXwDfApH/ay3AgHN6ao511svvmvxmS/o=
